# Generated by Django 4.1.1 on 2022-09-13 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_contributors',
            field=models.ManyToManyField(through='tickets.Contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
