# Generated by Django 4.1.1 on 2022-09-29 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_project_author_alter_contributors_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributors',
            new_name='Contributor',
        ),
    ]
